import type { Achievement } from "@/types/game";

export const ACHIEVEMENTS: Achievement[] = [
  { id: "ach_first_click", title: "Premier clic", description: "Effectue ton premier clic.", metric: "total_clicks", target: 1, icon: "MousePointer", bonus: 0.01 },
  { id: "ach_100_clicks", title: "Clickeur", description: "100 clics au total.", metric: "total_clicks", target: 100, icon: "MousePointer", bonus: 0.01 },
  { id: "ach_1000_clicks", title: "Machine à clics", description: "1000 clics au total.", metric: "total_clicks", target: 1000, icon: "Zap", bonus: 0.02 },
  { id: "ach_first_business", title: "Entrepreneur", description: "Achète ton premier business.", metric: "businesses_bought", target: 1, icon: "Building2", bonus: 0.01 },
  { id: "ach_5_business", title: "Portfolio", description: "Achète 5 business.", metric: "businesses_bought", target: 5, icon: "Layers", bonus: 0.02 },
  { id: "ach_20_business", title: "Conglomérat", description: "Achète 20 business au total.", metric: "businesses_bought", target: 20, icon: "Building", bonus: 0.03 },
  { id: "ach_first_invest", title: "Investisseur", description: "Fais ton premier investissement.", metric: "investments_made", target: 1, icon: "PieChart", bonus: 0.01 },
  { id: "ach_first_trade", title: "Trader", description: "Effectue ta première transaction.", metric: "trades_made", target: 1, icon: "LineChart", bonus: 0.01 },
  { id: "ach_10_trades", title: "Day trader", description: "10 transactions au marché.", metric: "trades_made", target: 10, icon: "Repeat", bonus: 0.02 },
  { id: "ach_first_mission", title: "Mission accomplie", description: "Complète ta première mission.", metric: "missions_completed", target: 1, icon: "CheckCircle", bonus: 0.01 },
  { id: "ach_10_missions", title: "Agent secret", description: "10 missions complétées.", metric: "missions_completed", target: 10, icon: "Target", bonus: 0.02 },
  { id: "ach_25_missions", title: "Maître des missions", description: "25 missions complétées.", metric: "missions_completed", target: 25, icon: "Trophy", bonus: 0.03 },
  { id: "ach_level_5", title: "Niveau 5", description: "Atteins le niveau 5.", metric: "level", target: 5, icon: "ArrowUp", bonus: 0.01 },
  { id: "ach_level_15", title: "Niveau 15", description: "Atteins le niveau 15.", metric: "level", target: 15, icon: "ArrowUp", bonus: 0.02 },
  { id: "ach_level_30", title: "Niveau 30", description: "Atteins le niveau 30.", metric: "level", target: 30, icon: "Crown", bonus: 0.03 },
  { id: "ach_cap_10k", title: "Dix mille", description: "Atteins 10 000 €.", metric: "best_capital", target: 10000, icon: "Star", bonus: 0.01 },
  { id: "ach_cap_1m", title: "Millionnaire", description: "Atteins 1M €.", metric: "best_capital", target: 1000000, icon: "Gem", bonus: 0.03 },
  { id: "ach_cap_1b", title: "Milliardaire", description: "Atteins 1B €.", metric: "best_capital", target: 1000000000, icon: "Sparkles", bonus: 0.05 },
  { id: "ach_golden_1", title: "Ruée dorée", description: "Déclenche Golden Rush.", metric: "golden_rushes", target: 1, icon: "Sparkles", bonus: 0.01 },
  { id: "ach_golden_10", title: "Or en série", description: "10 Golden Rush.", metric: "golden_rushes", target: 10, icon: "Sun", bonus: 0.02 },
  { id: "ach_combo_5", title: "Combo x5", description: "Atteins combo x5.", metric: "max_combo", target: 5, icon: "Flame", bonus: 0.01 },
  { id: "ach_combo_15", title: "Combo x15", description: "Atteins combo x15.", metric: "max_combo", target: 15, icon: "Flame", bonus: 0.02 },
  { id: "ach_prestige_1", title: "Renaissance", description: "Premier prestige.", metric: "prestige_count", target: 1, icon: "RefreshCw", bonus: 0.03 },
  { id: "ach_manager", title: "Manager", description: "Embauche un manager.", metric: "managers_hired", target: 1, icon: "UserPlus", bonus: 0.02 },
  { id: "ach_synergy", title: "Synergie", description: "Active une synergie.", metric: "synergies_active", target: 1, icon: "Link", bonus: 0.02 },
  { id: "ach_event_5", title: "Observateur", description: "5 événements vécus.", metric: "events_experienced", target: 5, icon: "Newspaper", bonus: 0.01 },
  { id: "ach_earned_100k", title: "Cent mille gagnés", description: "Gagne 100K € au total.", metric: "total_earned", target: 100000, icon: "Banknote", bonus: 0.02 },
  { id: "ach_spent_50k", title: "Grand dépensier", description: "Dépense 50K €.", metric: "total_spent", target: 50000, icon: "Wallet", bonus: 0.01 },
  { id: "ach_play_1h", title: "Une heure", description: "Joue 1 heure.", metric: "play_time", target: 3600, icon: "Clock", bonus: 0.01 },
  { id: "ach_play_5h", title: "Marathon", description: "Joue 5 heures.", metric: "play_time", target: 18000, icon: "Timer", bonus: 0.02 },
  { id: "ach_reputation_25", title: "Réputé", description: "25 points de réputation.", metric: "reputation", target: 25, icon: "Award", bonus: 0.02 },
  { id: "ach_daily_all", title: "Journée parfaite", description: "Complète tous les objectifs du jour.", metric: "daily_all", target: 1, icon: "Calendar", bonus: 0.03 },
  { id: "ach_secret_trillion", title: "Empire secret", description: "Atteins 1T €.", metric: "best_capital", target: 1000000000000, icon: "Rocket", bonus: 0.05, secret: true },
  { id: "ach_upgrade_10", title: "Optimiseur", description: "10 upgrades achetés.", metric: "upgrade_levels", target: 10, icon: "ArrowUpCircle", bonus: 0.02 },
  { id: "ach_income_500", title: "500/sec", description: "Atteins 500 €/sec.", metric: "income_per_sec", target: 500, icon: "TrendingUp", bonus: 0.02 },
];
