import type { GameEvent } from "@/types/game";

export const GAME_EVENTS: GameEvent[] = [
  {
    id: "boom",
    title: "Boom économique",
    description: "Les marchés sont en pleine euphorie. Profitez de la vague !",
    type: "positive",
    rarity: "uncommon",
    duration: 30,
    effects: { incomeMultiplier: 1.5, clickMultiplier: 1.3 },
  },
  {
    id: "crisis",
    title: "Crise temporaire",
    description: "Une légère contraction économique ralentit les revenus.",
    type: "negative",
    rarity: "common",
    duration: 25,
    effects: { incomeMultiplier: 0.85 },
  },
  {
    id: "opportunity",
    title: "Opportunité rare",
    description: "Une affaire exceptionnelle se présente !",
    type: "positive",
    rarity: "rare",
    duration: 0,
    effects: { cashBonus: 5000 },
  },
  {
    id: "viral",
    title: "Viralité",
    description: "Votre marque explose sur les réseaux sociaux !",
    type: "positive",
    rarity: "uncommon",
    duration: 20,
    effects: { incomeMultiplier: 1.8, clickMultiplier: 1.5 },
  },
  {
    id: "innovation",
    title: "Innovation breakthrough",
    description: "Une percée technologique booste vos business tech.",
    type: "positive",
    rarity: "rare",
    duration: 40,
    effects: { incomeMultiplier: 2 },
  },
  {
    id: "tax",
    title: "Taxe exceptionnelle",
    description: "L'État prélève une contribution temporaire.",
    type: "negative",
    rarity: "common",
    duration: 0,
    effects: { cashBonus: -0.02 },
  },
  {
    id: "cost_reduction",
    title: "Réduction des coûts",
    description: "Vos fournisseurs offrent des tarifs préférentiels.",
    type: "positive",
    rarity: "uncommon",
    duration: 60,
    effects: { costReduction: 0.15 },
  },
  {
    id: "investor",
    title: "Investisseur providentiel",
    description: "Un angel investor souhaite financer votre empire.",
    type: "choice",
    rarity: "epic",
    duration: 0,
    effects: {},
    choices: [
      { id: "accept", label: "Accepter", description: "+50K € mais -10% revenus 60s", effects: { cashBonus: 50000, incomeMultiplier: 0.9 } },
      { id: "refuse", label: "Refuser", description: "+5 réputation", effects: { riskChange: -2 } },
    ],
  },
  {
    id: "panic",
    title: "Panique boursière",
    description: "Le marché chute brutalement. Volatilité accrue.",
    type: "negative",
    rarity: "uncommon",
    duration: 30,
    effects: { marketVolatility: 2, assetImpact: { assetId: "moonbank", change: -0.15 } },
  },
  {
    id: "hype_tech",
    title: "Hype technologique",
    description: "L'IA est partout. NovaTech et NeuralSoft explosent.",
    type: "positive",
    rarity: "rare",
    duration: 25,
    effects: { assetImpact: { assetId: "novatech", change: 0.2 } },
  },
  {
    id: "crash_crypto",
    title: "Crash crypto fictif",
    description: "Les cryptos fictives chutent. Opportunité d'achat ?",
    type: "negative",
    rarity: "uncommon",
    duration: 20,
    effects: { marketVolatility: 1.5 },
  },
  {
    id: "productivity",
    title: "Bonus productivité",
    description: "Votre équipe est ultra-motivée aujourd'hui !",
    type: "positive",
    rarity: "common",
    duration: 15,
    effects: { clickMultiplier: 2, incomeMultiplier: 1.2 },
  },
  {
    id: "green_energy",
    title: "Révolution verte",
    description: "GreenGrid et OceanEnergy bénéficient du vent favorable.",
    type: "positive",
    rarity: "uncommon",
    duration: 30,
    effects: { assetImpact: { assetId: "greengrid", change: 0.12 } },
  },
  {
    id: "retail_boom",
    title: "Fête du shopping",
    description: "HyperRetail enregistre des ventes record.",
    type: "positive",
    rarity: "common",
    duration: 20,
    effects: { assetImpact: { assetId: "hyperretail", change: 0.1 } },
  },
  {
    id: "space_race",
    title: "Course spatiale",
    description: "AstroMining attire tous les investisseurs.",
    type: "positive",
    rarity: "rare",
    duration: 25,
    effects: { assetImpact: { assetId: "astromining", change: 0.25 } },
  },
  {
    id: "regulation",
    title: "Nouvelle régulation",
    description: "Des règles plus strictes augmentent légèrement le risque.",
    type: "negative",
    rarity: "common",
    duration: 45,
    effects: { riskChange: 3 },
  },
  {
    id: "merger",
    title: "Fusion géante",
    description: "Deux géants fusionnent. Le marché réagit positivement.",
    type: "positive",
    rarity: "epic",
    duration: 0,
    effects: { cashBonus: 25000 },
  },
  {
    id: "lucky_day",
    title: "Jour de chance",
    description: "Tout ce que vous touchez se transforme en or !",
    type: "positive",
    rarity: "legendary",
    duration: 10,
    effects: { clickMultiplier: 3, incomeMultiplier: 2.5 },
  },
  {
    id: "supply_chain",
    title: "Rupture supply chain",
    description: "Les coûts augmentent temporairement.",
    type: "negative",
    rarity: "uncommon",
    duration: 35,
    effects: { costReduction: -0.1 },
  },
  {
    id: "mentor",
    title: "Mentor milliardaire",
    description: "Un mentor vous offre des conseils précieux (+XP).",
    type: "positive",
    rarity: "rare",
    duration: 0,
    effects: { cashBonus: 10000 },
  },
  {
    id: "quantum_leap",
    title: "Saut quantique",
    description: "Quantum Motors annonce une percée révolutionnaire.",
    type: "positive",
    rarity: "epic",
    duration: 20,
    effects: { assetImpact: { assetId: "quantum_motors", change: 0.3 } },
  },
];

export const STRATEGIC_DECISIONS = [
  {
    id: "rd_invest",
    title: "Investir en R&D ?",
    description: "Votre équipe propose un gros investissement en recherche.",
    rarity: "uncommon" as const,
    choices: [
      { id: "invest", label: "Investir", description: "+15% revenus tech 120s, -20K €", effects: { cash: -20000, incomeBonus: 0.15, duration: 120 } },
      { id: "wait", label: "Attendre", description: "+3 réputation", effects: { reputation: 3 } },
      { id: "partner", label: "Partenariat", description: "+10K €, +5% risque", effects: { cash: 10000, risk: 5 } },
    ],
  },
  {
    id: "cost_cut",
    title: "Réduire les coûts ?",
    description: "Optimiser les dépenses pourrait libérer du capital.",
    rarity: "common" as const,
    choices: [
      { id: "aggressive", label: "Coupe agressive", description: "-15% coûts 90s, -5% revenus", effects: { incomeBonus: -0.05, duration: 90 } },
      { id: "balanced", label: "Équilibré", description: "-8% coûts 60s", effects: { duration: 60 } },
      { id: "reject", label: "Maintenir qualité", description: "+2 réputation", effects: { reputation: 2 } },
    ],
  },
  {
    id: "risk_take",
    title: "Prendre plus de risque ?",
    description: "Une opportunité à haut rendement se profile.",
    rarity: "rare" as const,
    choices: [
      { id: "all_in", label: "Tout miser", description: "+30K € ou -10K € (70% chance)", effects: { cash: 30000, risk: 15 } },
      { id: "moderate", label: "Mise modérée", description: "+10K €, +8% risque", effects: { cash: 10000, risk: 8 } },
      { id: "decline", label: "Refuser", description: "+5 réputation, -3% risque", effects: { reputation: 5, risk: -3 } },
    ],
  },
  {
    id: "expand_market",
    title: "Expansion internationale",
    description: "Ouvrir de nouveaux marchés demande des ressources.",
    rarity: "epic" as const,
    choices: [
      { id: "expand", label: "Expansion", description: "-50K €, +20% revenus 180s", effects: { cash: -50000, incomeBonus: 0.2, duration: 180 } },
      { id: "local", label: "Consolider local", description: "+8 réputation", effects: { reputation: 8 } },
    ],
  },
  {
    id: "hire_talent",
    title: "Recruter des talents",
    description: "Des experts de haut niveau sont disponibles.",
    rarity: "uncommon" as const,
    choices: [
      { id: "hire", label: "Recruter", description: "-15K €, +10% tous revenus 90s", effects: { cash: -15000, incomeBonus: 0.1, duration: 90 } },
      { id: "train", label: "Former interne", description: "+5K €, +2 réputation", effects: { cash: 5000, reputation: 2 } },
    ],
  },
];
