import type { Mission } from "@/types/game";

export const MISSIONS: Mission[] = [
  { id: "m_cap_1k", title: "Premier millier", description: "Atteins 1 000 € de capital — le vrai départ.", category: "beginner", target: 1000, metric: "capital", reward: 100, xpReward: 50, difficulty: 1, icon: "Target" },
  { id: "m_click_100", title: "Mains actives", description: "Génère 100 € en cliquant. Chaque clic compte.", category: "beginner", target: 100, metric: "click_earnings", reward: 50, xpReward: 30, difficulty: 1, icon: "MousePointer" },
  { id: "m_buy_3", title: "Petit portefeuille", description: "Possède 3 business différents.", category: "business", target: 3, metric: "unique_businesses", reward: 150, xpReward: 40, difficulty: 1, icon: "Building2" },
  { id: "m_income_100", title: "Flux constant", description: "Atteins 100 €/sec de revenu passif.", category: "growth", target: 100, metric: "income_per_sec", reward: 500, xpReward: 100, difficulty: 2, icon: "TrendingUp" },
  { id: "m_combo_10", title: "Combo master", description: "Atteins un combo x10.", category: "combo", target: 10, metric: "max_combo", reward: 200, xpReward: 60, difficulty: 2, icon: "Flame" },
  { id: "m_invest_1k", title: "Premier placement", description: "Investis 1 000 € au total.", category: "growth", target: 1000, metric: "total_invested", reward: 300, xpReward: 80, difficulty: 2, icon: "PieChart" },
  { id: "m_stock_5", title: "Actionnaire NovaTech", description: "Possède 5 actions NovaTech.", category: "trading", target: 5, metric: "stock_novatech", reward: 400, xpReward: 90, difficulty: 2, icon: "LineChart" },
  { id: "m_market_500", title: "Trader débutant", description: "Gagne 500 € sur le marché.", category: "trading", target: 500, metric: "market_profit", reward: 600, xpReward: 120, difficulty: 3, icon: "BarChart3" },
  { id: "m_rental", title: "Propriétaire", description: "Achète un appartement locatif.", category: "real_estate", target: 1, metric: "business_rental", reward: 800, xpReward: 100, difficulty: 2, icon: "Home" },
  { id: "m_saas", title: "SaaS débloqué", description: "Débloque le SaaS B2B.", category: "startup", target: 1, metric: "business_saas", reward: 1000, xpReward: 150, difficulty: 3, icon: "Cloud" },
  { id: "m_crisis", title: "Survivant", description: "Survis à une crise économique.", category: "risk", target: 1, metric: "survive_crisis", reward: 500, xpReward: 100, difficulty: 3, icon: "Shield" },
  { id: "m_cap_1m", title: "Millionnaire", description: "Atteins 1 000 000 € de capital.", category: "growth", target: 1000000, metric: "capital", reward: 10000, xpReward: 500, difficulty: 4, icon: "Crown" },
  { id: "m_upgrades_10", title: "Optimiseur", description: "Obtiens 10 upgrades.", category: "growth", target: 10, metric: "upgrade_count", reward: 2000, xpReward: 200, difficulty: 3, icon: "ArrowUpCircle" },
  { id: "m_passive_10k", title: "Machine à cash", description: "Génère 10K € en revenu passif cumulé.", category: "business", target: 10000, metric: "passive_earned", reward: 3000, xpReward: 250, difficulty: 3, icon: "Coins" },
  { id: "m_risky_2x", title: "Coup de poker", description: "Fais x2 sur un investissement risqué.", category: "risk", target: 2, metric: "investment_multiplier", reward: 5000, xpReward: 300, difficulty: 4, icon: "Dices" },
  { id: "m_millionaire", title: "Rang Millionnaire", description: "Atteins le titre Millionnaire.", category: "prestige", target: 1, metric: "milestone_m1m", reward: 15000, xpReward: 400, difficulty: 4, icon: "Trophy" },
  { id: "m_golden", title: "Ruée dorée", description: "Déclenche le mode Golden Rush.", category: "challenge", target: 1, metric: "golden_rush", reward: 1000, xpReward: 150, difficulty: 2, icon: "Sparkles" },
  { id: "m_clicks_50", title: "Clic foudre", description: "50 clics en 20 secondes.", category: "challenge", target: 50, metric: "clicks_in_20s", reward: 300, xpReward: 80, difficulty: 2, icon: "Zap" },
  { id: "m_ai_startup", title: "Visionnaire IA", description: "Achète une Startup IA.", category: "startup", target: 1, metric: "business_ai_startup", reward: 50000, xpReward: 600, difficulty: 5, icon: "Brain" },
  { id: "m_cap_1b", title: "Milliardaire", description: "Atteins 1B € et débloque le prestige.", category: "prestige", target: 1000000000, metric: "capital", reward: 100000, xpReward: 1000, difficulty: 5, icon: "Gem" },
  { id: "m_cap_10k", title: "Dix mille", description: "Atteins 10 000 €.", category: "beginner", target: 10000, metric: "capital", reward: 300, xpReward: 60, difficulty: 1, icon: "Star" },
  { id: "m_cap_100k", title: "Cent mille", description: "Atteins 100 000 €.", category: "growth", target: 100000, metric: "capital", reward: 1500, xpReward: 150, difficulty: 2, icon: "TrendingUp" },
  { id: "m_business_10", title: "Diversification", description: "Possède 10 business au total.", category: "business", target: 10, metric: "total_businesses", reward: 2000, xpReward: 180, difficulty: 3, icon: "Layers" },
  { id: "m_level_10", title: "Niveau 10", description: "Atteins le niveau 10.", category: "growth", target: 10, metric: "level", reward: 1000, xpReward: 200, difficulty: 2, icon: "ArrowUp" },
  { id: "m_level_25", title: "Niveau 25", description: "Atteins le niveau 25.", category: "growth", target: 25, metric: "level", reward: 5000, xpReward: 400, difficulty: 3, icon: "ArrowUp" },
  { id: "m_manager", title: "Recruteur", description: "Embauche ton premier manager.", category: "business", target: 1, metric: "managers_hired", reward: 2500, xpReward: 200, difficulty: 3, icon: "UserPlus" },
  { id: "m_synergy", title: "Synergie active", description: "Active une synergie entre business.", category: "business", target: 1, metric: "synergies_active", reward: 3000, xpReward: 250, difficulty: 3, icon: "Link" },
  { id: "m_achievement_5", title: "Collectionneur", description: "Débloque 5 achievements.", category: "challenge", target: 5, metric: "achievements", reward: 1500, xpReward: 150, difficulty: 2, icon: "Award" },
  { id: "m_daily_3", title: "Journée productive", description: "Complète 3 objectifs quotidiens.", category: "daily", target: 3, metric: "daily_completed", reward: 2000, xpReward: 200, difficulty: 2, icon: "Calendar" },
  { id: "m_reputation_50", title: "Réputation établie", description: "Atteins 50 points de réputation.", category: "prestige", target: 50, metric: "reputation", reward: 5000, xpReward: 300, difficulty: 3, icon: "Star" },
  { id: "m_trade_20", title: "Trader actif", description: "Effectue 20 transactions.", category: "trading", target: 20, metric: "trades_made", reward: 1500, xpReward: 150, difficulty: 2, icon: "Repeat" },
  { id: "m_event_10", title: "Observateur", description: "Vis 10 événements économiques.", category: "challenge", target: 10, metric: "events_experienced", reward: 1000, xpReward: 120, difficulty: 2, icon: "Newspaper" },
  { id: "m_prestige_1", title: "Renaissance", description: "Effectue ton premier prestige.", category: "prestige", target: 1, metric: "prestige_count", reward: 50000, xpReward: 800, difficulty: 5, icon: "RefreshCw" },
  { id: "m_clicks_1000", title: "Mille clics", description: "Effectue 1000 clics au total.", category: "combo", target: 1000, metric: "total_clicks", reward: 2000, xpReward: 200, difficulty: 2, icon: "MousePointer" },
  { id: "m_income_1k", title: "Mille par seconde", description: "Atteins 1 000 €/sec.", category: "growth", target: 1000, metric: "income_per_sec", reward: 10000, xpReward: 400, difficulty: 4, icon: "Rocket" },
  { id: "m_income_10k", title: "Dix mille par seconde", description: "Atteins 10 000 €/sec.", category: "growth", target: 10000, metric: "income_per_sec", reward: 50000, xpReward: 600, difficulty: 5, icon: "Zap" },
  { id: "m_orbital", title: "Conquête spatiale", description: "Achète l'Empire orbital.", category: "startup", target: 1, metric: "business_orbital", reward: 500000, xpReward: 1000, difficulty: 5, icon: "Rocket" },
  { id: "m_decision", title: "Décideur", description: "Prends 5 décisions stratégiques.", category: "challenge", target: 5, metric: "decisions_made", reward: 3000, xpReward: 250, difficulty: 3, icon: "GitBranch" },
  { id: "m_spent_100k", title: "Grand investisseur", description: "Dépense 100 000 € au total.", category: "growth", target: 100000, metric: "total_spent", reward: 5000, xpReward: 300, difficulty: 3, icon: "Wallet" },
  { id: "m_earned_1m", title: "Million gagné", description: "Gagne 1M € au total.", category: "growth", target: 1000000, metric: "total_earned", reward: 20000, xpReward: 500, difficulty: 4, icon: "Banknote" },
];
